"use client"
import type { Metadata } from "next";
import { usePathname } from "next/navigation";
import { getPageConfig } from "@/lib/config/dashboard-config";
import { Sidebar } from '@/components/sidebar';
import {Navbar} from "@/components/navbar";
import { useSidebar } from "@/contexts/sideBarContext";



//export const metadata: Metadata = {
//  title: "Create Next App",
 // description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  //to get current page configuration.
  const currentPageConfig = getPageConfig(pathname) || { title: "Dashboard", subtitle: "Overview" } ;
  const {isCollapsedDesktop} = useSidebar();

  return (
    
      <main >
        <div className="bg-white  flex w-full ">
          <div className="bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50 mr-5 ml-5 mt-2 mb-20 item-center justify-center ">
               <Sidebar/> 

          </div>
          {/**main content */}
          <div  className="w-[80vh] h-[80vh] flex-1 flex flex-col ">
            {/* <Navbar
             title={currentPageConfig.title} 
             icon={currentPageConfig.icon} 
            /> */}
           <div className={`  flex flex-col  w-contain h-contain bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50  ${isCollapsedDesktop ? "lg:ml-[70px]" : "lg:ml-[250px]"}`}>
            {children}
           </div>
          </div>
        </div>
      </main>

  );
}
