"use client";
import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/contexts/sideBarContext";
import { usePathname } from "next/navigation";
import { getPageConfig } from "@/lib/config/dashboard-config";
import { MiniSideBarProvider } from "@/contexts/miniSideBarContext";
import QueryProvider from "@/provider/queryProvider";

//export const metadata: Metadata = {
//  title: "Create Next App",
// description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();
  //to get current page configuration.
  //const currentPageConfig = getPageConfig(pathname) || { title: "Dashboard", subtitle: "Overview" } ;

  return (
    <html lang="en">
      <SidebarProvider>
        <MiniSideBarProvider>
          <body>
            <QueryProvider>{children}</QueryProvider>
          </body>
        </MiniSideBarProvider>
      </SidebarProvider>
    </html>
  );
}
