"use client"
import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/contexts/sideBarContext";
import { usePathname } from "next/navigation";
import { getPageConfig } from "@/lib/config/dashboard-config";
import { Sidebar } from '@/components/sidebar';
import {Navbar} from "@/components/navbar";



//export const metadata: Metadata = {
//  title: "Create Next App",
 // description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  //to get current page configuration.
  const currentPageConfig = getPageConfig(pathname) || { title: "Dashboard", subtitle: "Overview" } ;

  return (
    <html lang="en">
      <SidebarProvider>
      <body >
        <div className="flex w-full ">
          {/* <Sidebar/> */}
            <Sidebar/>
          {/**main content */}
          <div  className="w-full flex-1 flex flex-col ">
            <Navbar
             title={currentPageConfig.title} 
             icon={currentPageConfig.icon} 
            />
            {children}
          </div>
        </div>
      </body>
      </SidebarProvider>
    </html>
  );
}
